### ISSUE TITLE
Low update rates of Point Cloud on N35 camera

### ISSUE THREAD

**Issue by Danfoa** [ensenso/ros_driver#11]
I am using two N35 cameras, which by specification can reach a speed of **10 fps** of 3D data, but I am experimenting update times greater than **1.6** seconds for a single camera and **2.8** seconds for both cameras running at the same time.

My `request_data` action are requesting only `point_cloud` and `normals`. 

Now my question is: 
- The [Max. fps (3D): 10 (2x Binning: 30) and 64 disparity levels](https://en.ids-imaging.com/ensenso-n35.html) statement from the N35 description talks about 10 fps of disparity map (if I am not wrong), but there is no information on the update rate of point cloud computed in the inbound computer, are the times that I am experiencing normal?

I tried requesting the data from both cameras in a single thread and in separate threads, but this does not seem to have much influence on the update times.  

PS: I am currently concatenating both cameras point cloud using PCL after receiving both cameras data separately, but I am aware there is a way of doing the combination of both point clouds on the cameras computers [Output of a single 3D point cloud with data from all cameras used in multi-camera mode](https://en.ids-imaging.com/ensenso-n35.html), is this possible with the `ros_driver`? I have already used the `target_frame` parameter from the ensenso_camera nodes to obtain both cameras pointcloud on the same reference frame.

PPS: I have already increased the network card input buffer to the maximum `4096`, but there is no noticeable change.

**Comment by saierd** [comment]
Yes, the FPS are specified for the disparity map. Computing the point map and normals does take a bit extra time, but that is usually ~20ms per frame.

Generally, the FPS you can achieve varies significantly depending on your settings and hardware. Your processing times certainly are on the slower side. There is an overview of the most important parameters and their impact on performance in the [manual](https://www.ensenso.com/manual/index.html?performance_quality_settings.htm). If you open the camera in NxView, you can also see the time that the different parts of the processing take on the top right of the window (click on `Point Cloud (Z Channel)` and enable the `Normals` checkbox to compute all data that you are currently requesting in ROS).

When you have both cameras running at the same time, you should connect them through different network interfaces, if possible, and either do the processing sequentially or maybe limit the number of threads each of the camera nodes can use.

Using the ROS nodes also has some overhead, especially if you don't use the nodelet. In that case, the point cloud needs to be serialized and deserialized in order to send it in ROS messages.

If you have more questions regarding the performance, you can create a log (using `Tools` > `Profiling...` in NxView) and send it to me by mail (daniel.saier@ensenso.com). I can analyze it and tell you why your processing is taking longer than expected.

---

Regarding the point clouds, the ROS node currently has no method to merge them, as each camera node can only control one camera. It might be useful to provide an additional node that does the merging.
