### ISSUE TITLE
Unable to receive depth image from linked Ensenso camera

### ISSUE THREAD

**Issue by jdzied** [ensenso/ros_driver#35]
Hi, I am trying to receive a depth image from a calibrated pair of Ensenso N35 and UEye RGB Camera but get the following Error: 
`Depth images are not yet supported for linked and multi camera usage. Only request depth images when using one stereo camera only.` 
I can only receive the colourized pointcloud. Is there any way to get the depth and color image seperately?

Thanks in advance!

**Comment by yguenduez** [comment]
Hello Jonathan :)

The error message is not quite correct, I will correct that.

The depth map can only be requested, if the `camera_frame` is the same as the `target_frame`.
This is because we receive the depth map out of the point cloud given from the NxLib (we only use the z-Channel of the point cloud). And if the camera is externally calibrated, the point cloud is automatically transformed to this given frame, so the depth map would not be correct.

I will add the feature, that you can receive the depth map regardless of frames and transformations. But for now there is only the following solution:

In order to have them separated, you can link calibrate the mono camera to the stereo camera, but you must not add any external transformation to the stereo camera (i.e. hand-eye calibration, workspace calibration). 
Also you must not define any frames of the stereo camera in the launch file, so the `camera_frame` is the same as the `target_frame`. Then you should get a depth map from the stereo camera.

I hope I could help. Tell me if you have problems. (And greetings to the IFL!)
