### ISSUE TITLE
how to change the resolution of the depth image?

### ISSUE THREAD

**Issue by robopassio** [ensenso/ros_driver#96]
The default w x h = 1280 x 1024.
How can we change it to other values? Any other options for the resolution?

**Comment by saierd** [comment]
The 3D data has the resolution of the camera sensor by default, since we compute a depth for each of the camera pixels.

You can change it by adjusting camera parameters like binning, scaling and AOI. See [this tutorial](http://wiki.ros.org/ensenso_driver/Tutorials/Parameters) for how to set parameters.
